title: JP Times - Ελλάς
email: john@prantalos.gr
description: >-
  Αναρτήσεις για εμπειρίες, απόψεις, προγραμματιστικά θέματα και που και που
  gaming και VR.
international_url: "https://prantalos.com"
baseurl: "/"
author: John Prantalos

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-environment-variables

show_excerpts: true

# languages: ["en", "el"]
# languageNames:
#   en: English
#   el: Greek
# exclude_from_localizations: ["assets", "images", "css"]
# default_lang: en
# default_locale_in_subfolder: false
sass:
    sass_dir: _sass

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      is_post: true

permalink: δημοσίευση/:year/:month/:day/:title:output_ext
paginate_path: "/σελίδα/:num/"
pagination:
  enabled: true
  per_page: 10
  offset: 0
  permalink: "/σελίδα/:num/"
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
