version: '3'
services:
  jekyll:
      platform: linux/amd64
      container_name: ${COMPOSE_PROJECT_NAME}-${JEKYLL_ENV}
      build:
        context: ../
        dockerfile: ./.docker/Dockerfile
      environment:
        - JEKYLL_ENV=${JEKYLL_ENV}
      command: bundle exec jekyll serve --watch --incremental --config _config.yml _config-${JEKYLL_ENV}.yml --host 0.0.0.0
      ports:
          - 4000:4000
      volumes:
          - ..:/srv/jekyll:cached
          - ../vendor/bundle:/usr/local/bundle:cached